package com.lmash.mysqltest.mapper;

import com.lmash.mysqltest.pojo.Integral;
import com.lmash.mysqltest.pojo.IntegralExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IntegralMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    long countByExample(IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    int deleteByExample(IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    int deleteByPrimaryKey(Integer integralId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    int insert(Integral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    int insertSelective(Integral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    List<Integral> selectByExample(IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    Integral selectByPrimaryKey(Integer integralId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    int updateByExampleSelective(@Param("record") Integral record, @Param("example") IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    int updateByExample(@Param("record") Integral record, @Param("example") IntegralExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    int updateByPrimaryKeySelective(Integral record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    int updateByPrimaryKey(Integral record);
}