package com.lmash.mysqltest.mapper;

import com.lmash.mysqltest.pojo.Setting;
import com.lmash.mysqltest.pojo.SettingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    long countByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int deleteByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int deleteByPrimaryKey(Integer setId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int insert(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int insertSelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    List<Setting> selectByExampleWithBLOBs(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    List<Setting> selectByExample(SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    Setting selectByPrimaryKey(Integer setId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int updateByExampleSelective(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int updateByExample(@Param("record") Setting record, @Param("example") SettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int updateByPrimaryKeySelective(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Setting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_setting
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    int updateByPrimaryKey(Setting record);
}