package com.lmash.mysqltest.mapper;

import com.lmash.mysqltest.pojo.Task;
import com.lmash.mysqltest.pojo.TaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    long countByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    int deleteByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    int deleteByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    int insert(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    int insertSelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    List<Task> selectByExample(TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    Task selectByPrimaryKey(Integer taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    int updateByExample(@Param("record") Task record, @Param("example") TaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    int updateByPrimaryKeySelective(Task record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_task
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    int updateByPrimaryKey(Task record);
}