package com.lmash.mysqltest.mapper;

import com.lmash.mysqltest.pojo.User;
import com.lmash.mysqltest.pojo.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import org.springframework.stereotype.Service;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    User selectByPrimaryKey(Integer userId);

    int queryCountUserByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x_user
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    int updateByPrimaryKey(User record);
}