package com.lmash.mysqltest.pojo;

import java.util.Date;

public class Integral {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_integral.integral_id
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    private Integer integralId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_integral.integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_integral.integral_behavior
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    private Integer integralBehavior;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_integral.integral_date
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    private Date integralDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_integral.user_id
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_integral.information
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    private String information;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_integral.integral_id
     *
     * @return the value of x_integral.integral_id
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public Integer getIntegralId() {
        return integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_integral.integral_id
     *
     * @param integralId the value for x_integral.integral_id
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public void setIntegralId(Integer integralId) {
        this.integralId = integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_integral.integral
     *
     * @return the value of x_integral.integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_integral.integral
     *
     * @param integral the value for x_integral.integral
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_integral.integral_behavior
     *
     * @return the value of x_integral.integral_behavior
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public Integer getIntegralBehavior() {
        return integralBehavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_integral.integral_behavior
     *
     * @param integralBehavior the value for x_integral.integral_behavior
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public void setIntegralBehavior(Integer integralBehavior) {
        this.integralBehavior = integralBehavior;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_integral.integral_date
     *
     * @return the value of x_integral.integral_date
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public Date getIntegralDate() {
        return integralDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_integral.integral_date
     *
     * @param integralDate the value for x_integral.integral_date
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public void setIntegralDate(Date integralDate) {
        this.integralDate = integralDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_integral.user_id
     *
     * @return the value of x_integral.user_id
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_integral.user_id
     *
     * @param userId the value for x_integral.user_id
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_integral.information
     *
     * @return the value of x_integral.information
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public String getInformation() {
        return information;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_integral.information
     *
     * @param information the value for x_integral.information
     *
     * @mbg.generated Thu Oct 17 10:34:03 CST 2019
     */
    public void setInformation(String information) {
        this.information = information == null ? null : information.trim();
    }
}