package com.lmash.mysqltest.pojo;

import java.util.Date;

public class Setting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_setting.set_id
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    private Integer setId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_setting.set_type
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    private Integer setType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_setting.set_val
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    private String setVal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_setting.remark
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_setting.ordid
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    private Integer ordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_setting.create_time
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_setting.update_time
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_setting.set_content
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    private String setContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_setting.set_id
     *
     * @return the value of x_setting.set_id
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public Integer getSetId() {
        return setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_setting.set_id
     *
     * @param setId the value for x_setting.set_id
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public void setSetId(Integer setId) {
        this.setId = setId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_setting.set_type
     *
     * @return the value of x_setting.set_type
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public Integer getSetType() {
        return setType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_setting.set_type
     *
     * @param setType the value for x_setting.set_type
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public void setSetType(Integer setType) {
        this.setType = setType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_setting.set_val
     *
     * @return the value of x_setting.set_val
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public String getSetVal() {
        return setVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_setting.set_val
     *
     * @param setVal the value for x_setting.set_val
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public void setSetVal(String setVal) {
        this.setVal = setVal == null ? null : setVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_setting.remark
     *
     * @return the value of x_setting.remark
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_setting.remark
     *
     * @param remark the value for x_setting.remark
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_setting.ordid
     *
     * @return the value of x_setting.ordid
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public Integer getOrdid() {
        return ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_setting.ordid
     *
     * @param ordid the value for x_setting.ordid
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public void setOrdid(Integer ordid) {
        this.ordid = ordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_setting.create_time
     *
     * @return the value of x_setting.create_time
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_setting.create_time
     *
     * @param createTime the value for x_setting.create_time
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_setting.update_time
     *
     * @return the value of x_setting.update_time
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_setting.update_time
     *
     * @param updateTime the value for x_setting.update_time
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_setting.set_content
     *
     * @return the value of x_setting.set_content
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public String getSetContent() {
        return setContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_setting.set_content
     *
     * @param setContent the value for x_setting.set_content
     *
     * @mbg.generated Thu Oct 17 10:36:12 CST 2019
     */
    public void setSetContent(String setContent) {
        this.setContent = setContent == null ? null : setContent.trim();
    }
}