package com.lmash.mysqltest.pojo;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_task.task_id
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    private Integer taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_task.task_name
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_task.is_complete
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    private String isComplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_task.integral
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_task.user_id
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_task.task_id
     *
     * @return the value of x_task.task_id
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_task.task_id
     *
     * @param taskId the value for x_task.task_id
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_task.task_name
     *
     * @return the value of x_task.task_name
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_task.task_name
     *
     * @param taskName the value for x_task.task_name
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_task.is_complete
     *
     * @return the value of x_task.is_complete
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public String getIsComplete() {
        return isComplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_task.is_complete
     *
     * @param isComplete the value for x_task.is_complete
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public void setIsComplete(String isComplete) {
        this.isComplete = isComplete == null ? null : isComplete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_task.integral
     *
     * @return the value of x_task.integral
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_task.integral
     *
     * @param integral the value for x_task.integral
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_task.user_id
     *
     * @return the value of x_task.user_id
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_task.user_id
     *
     * @param userId the value for x_task.user_id
     *
     * @mbg.generated Thu Oct 17 10:35:14 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}