package com.lmash.mysqltest.pojo;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.user_id
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.pid
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.company_id
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.nick_name
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.password
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.gender
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.avatar_url
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.country
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.province
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.city
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.openid
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String openid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.unionid
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String unionid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.user_name
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.id_card
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.points
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Integer points;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.is_manager
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Byte isManager;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.state
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.last_study_video_id
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Integer lastStudyVideoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.invitation_code
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String invitationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.wxacode_url
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private String wxacodeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.study_total_second
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Integer studyTotalSecond;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.create_time
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column x_user.update_time
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.user_id
     *
     * @return the value of x_user.user_id
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.user_id
     *
     * @param userId the value for x_user.user_id
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.pid
     *
     * @return the value of x_user.pid
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.pid
     *
     * @param pid the value for x_user.pid
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.company_id
     *
     * @return the value of x_user.company_id
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.company_id
     *
     * @param companyId the value for x_user.company_id
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.nick_name
     *
     * @return the value of x_user.nick_name
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.nick_name
     *
     * @param nickName the value for x_user.nick_name
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.password
     *
     * @return the value of x_user.password
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.password
     *
     * @param password the value for x_user.password
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.gender
     *
     * @return the value of x_user.gender
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.gender
     *
     * @param gender the value for x_user.gender
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.avatar_url
     *
     * @return the value of x_user.avatar_url
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.avatar_url
     *
     * @param avatarUrl the value for x_user.avatar_url
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.country
     *
     * @return the value of x_user.country
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.country
     *
     * @param country the value for x_user.country
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.province
     *
     * @return the value of x_user.province
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.province
     *
     * @param province the value for x_user.province
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.city
     *
     * @return the value of x_user.city
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.city
     *
     * @param city the value for x_user.city
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.openid
     *
     * @return the value of x_user.openid
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.openid
     *
     * @param openid the value for x_user.openid
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.unionid
     *
     * @return the value of x_user.unionid
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.unionid
     *
     * @param unionid the value for x_user.unionid
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.user_name
     *
     * @return the value of x_user.user_name
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.user_name
     *
     * @param userName the value for x_user.user_name
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.id_card
     *
     * @return the value of x_user.id_card
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.id_card
     *
     * @param idCard the value for x_user.id_card
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.points
     *
     * @return the value of x_user.points
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Integer getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.points
     *
     * @param points the value for x_user.points
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setPoints(Integer points) {
        this.points = points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.is_manager
     *
     * @return the value of x_user.is_manager
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Byte getIsManager() {
        return isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.is_manager
     *
     * @param isManager the value for x_user.is_manager
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setIsManager(Byte isManager) {
        this.isManager = isManager;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.state
     *
     * @return the value of x_user.state
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.state
     *
     * @param state the value for x_user.state
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.last_study_video_id
     *
     * @return the value of x_user.last_study_video_id
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Integer getLastStudyVideoId() {
        return lastStudyVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.last_study_video_id
     *
     * @param lastStudyVideoId the value for x_user.last_study_video_id
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setLastStudyVideoId(Integer lastStudyVideoId) {
        this.lastStudyVideoId = lastStudyVideoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.invitation_code
     *
     * @return the value of x_user.invitation_code
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getInvitationCode() {
        return invitationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.invitation_code
     *
     * @param invitationCode the value for x_user.invitation_code
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setInvitationCode(String invitationCode) {
        this.invitationCode = invitationCode == null ? null : invitationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.wxacode_url
     *
     * @return the value of x_user.wxacode_url
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public String getWxacodeUrl() {
        return wxacodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.wxacode_url
     *
     * @param wxacodeUrl the value for x_user.wxacode_url
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setWxacodeUrl(String wxacodeUrl) {
        this.wxacodeUrl = wxacodeUrl == null ? null : wxacodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.study_total_second
     *
     * @return the value of x_user.study_total_second
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Integer getStudyTotalSecond() {
        return studyTotalSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.study_total_second
     *
     * @param studyTotalSecond the value for x_user.study_total_second
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setStudyTotalSecond(Integer studyTotalSecond) {
        this.studyTotalSecond = studyTotalSecond;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.create_time
     *
     * @return the value of x_user.create_time
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.create_time
     *
     * @param createTime the value for x_user.create_time
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column x_user.update_time
     *
     * @return the value of x_user.update_time
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column x_user.update_time
     *
     * @param updateTime the value for x_user.update_time
     *
     * @mbg.generated Thu Oct 17 10:34:48 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}